### ISSUE TITLE
Use of non local resources

### ISSUE THREAD

**Issue by fahminlb33** [fahminlb33/Venjix#12]
I just noticed that the new PR #5 is adding this line:

https://github.com/fahminlb33/Venjix/blob/2e78a33bf1c8347df1a3fbb17a89d8b7bc8b5417/Views/Shared/_Layout.cshtml#L21

It's not bad per se but it's better to use libman to download and use the library locally, so this app can be more portable in case of no internet connection.

**Comment by fahminlb33** [comment]
@rasyidf Maybe you wanna take a look at this issue.

**Comment by fahminlb33** [comment]
Another thing, is this icon pack necessary? Can we just use one? Either use FontAwesome or Feater Icons, don't use both as it will slow down the web and adds extra dependecies.

**Comment by rasyidf** [comment]
I guess feather icons is much smaller than Fontawesome, unfortunately, Bootstrap <= 4.5 are tightly coupled with FontAwesome, and making it harder to separate.

**Comment by fahminlb33** [comment]
I've included Feather Icon in the commit 3c35add05176f78f117cb97676105fb252caf252
But why do we need separate icon pack? Can we just use FontAwesome instead?

**Comment by rasyidf** [comment]
Icons are designed to meet some use cases, while font-awesome is broadly used in small web iconography, and because of its legacy icons being converted to vector, it lacks of scalability. In terms of style, there are ionic, iconic, feathers, fluent and bootstrap Icons that uses `svg` and designed with scalability in mind, big icons and small one have good proportion.

Well, we can gradually remove font-awesome, for the sake of UI consistency.  AFAIK, the bootstrap icons that tightly coupled were only at some chevron expander icon.

**Comment by fahminlb33** [comment]
Okay, I understand your point of view, that's just from my point of view from optimization, but I lack UI/UX experience so I'm sorry for that.
I'll close this issue now.
